# Generated by Django 3.2 on 2021-05-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('per', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('oopen', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('vol', models.BigIntegerField()),
            ],
        ),
    ]
